# Use an official Python runtime as a parent image
FROM python:3.12 as builder

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY Pipfile Pipfile.lock /code/
RUN pip install --no-cache-dir pipenv \
    && pipenv requirements > requirements.txt

# Start a new stage
FROM python:3.12

# Set work directory
WORKDIR /code

# Copy requirements.txt from the previous stage
COPY --from=builder /code/requirements.txt /code/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /code
COPY . /code/

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the command to start uWSGI
CMD ["uwsgi", "--https", ":8000", "--module", ".wsgi"]