# Generated by Django 5.0.4 on 2024-04-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'default_related_name': 'labels',
            },
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='title',
            field=models.TextField(default=None, help_text='Enter the title of the article', null=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='labels',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='blog_articles', to='content_management.label'),
        ),
    ]
