# Generated by Django 4.2.6 on 2023-10-08 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_alter_blogarticle_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='node',
            field=models.ForeignKey(limit_choices_to={'node_type': 3}, on_delete=django.db.models.deletion.CASCADE, to='content_management.blognode'),
        ),
    ]
