# Generated by Django 4.2.6 on 2023-10-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_alter_blogarticle_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='language_independent',
            field=models.BooleanField(default=False, help_text='Select this option, if you want to disable language dependency instance wise'),
        ),
    ]
