# Generated by Django 5.0.4 on 2024-05-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_alter_blogarticle_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='labels',
            field=models.ManyToManyField(blank=True, default=None, related_name='blog_articles', to='content_management.label'),
        ),
    ]
